---
apiVersion: v1
kind: Service
metadata:
  name: bind9-service
  labels:
    app: bind9
spec:
  externalIPs:
  - 192.168.11.4
  - 192.168.11.5
  selector:
    app: bind9
  ports:
  - port: 53
    targetPort: 53
    name: bind9
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bind9-deployment
  labels:
    app: bind9
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bind9
  template:
    metadata:
      labels:
        app: bind9
    spec:
      hostNetwork: true
      containers:
      - name: bind9
        image: ubuntu/bind9
        env:
        - name: TZ
          value: UTC
        ports:
        - containerPort: 53
          hostPort: 53
          name: dns
